  # Deployment job
deploy:
  environment:
    name: Google Cloud
      url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to Google Cloud
      id: deployment
      uses: actions/deploy-pages@v2
